### ISSUE TITLE
Unable to run Selenium server using rsDriver function

### ISSUE THREAD

**Issue by farrarthomas** [ropensci/wdman#10]
Please fill the following template:

### OS
Windows 8.1 Pro, 64 bit
Running R version 3.2.2

### Expected behaviour
I want to run RSelenium for the first time (the end goal is to use it for web scraping). I cannot use Docker because it requires Windows 10. Hence I tried to follow the instructions on the RSeleneium vignette for using the rsDriver function to run a Selenium Server.

### Actual behaviour and steps to reproduce:
When I run the command 
`rD<-rsDriver(verbose=FALSE)`
I get the following error dialogue popping up: 

> The procedure entry point R_GetConnection could not be located in the dynamic link library C:/Users/tom/Documents/R/win-library/3.2/jsonlite/libs/i386/jsonlite.dll

The error message in the R Console itself is:

> Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/tom/Documents/R/win-library/3.2/jsonlite/libs/i386/jsonlite.dll':
  LoadLibrary failure:  The specified procedure could not be found.

That file does exist in that folder however.

As a Plan B, I tried to download a Selenium Server binary (2.53.0) and run the jar. I then ran the following R code:
`remDr<-remoteDriver$new()
remDr$open()`

This yielded the same error dialogue and the following error in the R Console:

>  "Connecting to remote server"
Error in checkError(res) : 
  Undefined error in httr call. httr output: unable to load shared object 'C:/Users/tom/Documents/R/win-library/3.2/jsonlite/libs/i386/jsonlite.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Assistance is greatly appreciated since I am well versed in R but not in web interfacing.

**Comment by johndharrison** [comment]
wdman depends on the binman package which requires a version of R >= 3.3. Thou from the error it appears you have an issue with your install of the jsonlite package.
