### ISSUE TITLE
Unable to download selenium server

### ISSUE THREAD

**Issue by ghost** [ropensci/wdman#13]
**Operating System**
Mac 10.12
R version 3.4.0

**Expected behaviour**
I would expect rsDriver to be able to have the chrome server running after the following commands:

```
library(RSelenium)
rD <- rsDriver()
```

But I continued to get error

```
checking Selenium Server versions:
BEGIN: PREDOWNLOAD
Error in open.connection(con, "rb") : Timeout was reached
```

Any help is appreciated!

**Comment by trevorpatch** [comment]
I have something similar:

```
library(RSelenium)
library(wdman)
pjsDrv <- phantomjs(verbose = FALSE, check = FALSE)
rD <- rsDriver(browser = "phantomjs")

```

```
checking Selenium Server versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking chromedriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking geckodriver versions:
BEGIN: PREDOWNLOAD
Error in open.connection(con, "rb") : HTTP error 403.
```

**Comment by johndharrison** [comment]
It is most likely something local to your network. Running the rsDriver function from my location does not result in a 403.

**Comment by ghost** [comment]
I‘m from China. There is a Great Firewall to block some website, such as Twitter, Facebook. But after using VPN or shadowsocks, I unblock Twitter and other blocked website. But I still can't download the driver. Is there any method to make rsDriver function download normally? Any help is appreciated!

**Comment by rafaleo** [comment]
I have the same issue today while it worked for long time; The same comunicat as @bloynoys 
the code is: `rS <- rsDriver(browser = "phantomjs", port = 4563L, version = "3.7.1")`

I need to do my work! What to do?

**Comment by rafaleo** [comment]
phew! I restarted R and was ok. False alarm.

**Comment by dklinenberg2020** [comment]
> I have something similar:
> 
> ```
> library(RSelenium)
> library(wdman)
> pjsDrv <- phantomjs(verbose = FALSE, check = FALSE)
> rD <- rsDriver(browser = "phantomjs")
> ```
> 
> ```
> checking Selenium Server versions:
> BEGIN: PREDOWNLOAD
> BEGIN: DOWNLOAD
> BEGIN: POSTDOWNLOAD
> checking chromedriver versions:
> BEGIN: PREDOWNLOAD
> BEGIN: DOWNLOAD
> BEGIN: POSTDOWNLOAD
> checking geckodriver versions:
> BEGIN: PREDOWNLOAD
> Error in open.connection(con, "rb") : HTTP error 403.
> ```

I'm also having this problem What was the solution?
