### ISSUE TITLE
Bug in java_check

### ISSUE THREAD

**Issue by Libum** [ropensci/wdman#15]
Hi, I think I noticed a small bug in java_check function from selenium.R:

```
java_check <- function(){
  javapath <- Sys.which("java")
  if(identical(javapath, "")){
    stop("PATH to JAVA not found. Please check JAVA is installed.")
  }
  javapath
}
```

Sys.which always returns named vector, so condition in if statement always evaluates to False, even if Java is not defined in the PATH. It resulted in not very informative error, when I tried to run selenium() function on machine with no Java in the system path.

**Comment by johndharrison** [comment]
Thanks @Libum for spotting this. Fixed ba3683d3e02
