### ISSUE TITLE
Could Not Create Process / Access is denied

### ISSUE THREAD

**Issue by ghost** [ropensci/wdman#18]
Please fill the following template:

### Operating System 
Windows 10

### Please describe Expected behaviour 
Task Scheduler runs batch script launching R script for execution.

### Please describe Actual behaviour
Task Scheduler runs batch script which does launch the R script, but the execution fails when launching the chrome driver.

### Steps to reproduce the behaviour
Scheduled task in Windows 10 launching R Script with underlying wdman/chrome driver instructions. Also had similar experience when attempting PhantomJS. Script runs fine when executing batch file outside of Task Scheduler. Attempted all kinds of modifications to ensure User has Administrative rights running batch with highest privileges.

Additional: 
Error from Log:

Loading required package: rJava
Loading required package: xlsxjars
**Error in subprocess::spawn_process(tfile, ...) : 
  could not create process: Access is denied
Calls: chrome ... spawn_tofile -> windows_spawn_tofile -> <Anonymous>
Execution halted**

Thanks for your efforts with this package which is fantastic. Appreciate any assistance or guidance you can offer. Regards, John

**Comment by jonathanvoelkle** [comment]
Closing as no longer relevant (all code has been migrated to use processx)
