### ISSUE TITLE
unable to download files in headless chrome

### ISSUE THREAD

**Issue by yonicd** [ropensci/wdman#19]
trying to reproduce these steps in wdman startup to get around headless chrome 59 bug

https://bugs.chromium.org/p/chromium/issues/detail?id=696481#c80

### Operating System

macOS

```r
binman::list_versions('chromedriver')
$mac64
[1] "2.38" "2.39" "2.40" "2.41"
```

<details>

<summary> Session Info </summary>

```r
> devtools::session_info()
Session info --------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.2.779)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-07-29                  

Packages ------------------------------------------------------------------------------------------
 package     * version   date       source                             
 assertthat    0.2.0     2017-04-11 CRAN (R 3.5.0)                     
 base        * 3.5.0     2018-04-24 local                              
 base64enc     0.1-3     2015-07-28 CRAN (R 3.5.0)                     
 binman        0.1.1     2018-07-18 cran (@0.1.1)                      
 bitops        1.0-6     2013-08-17 CRAN (R 3.5.0)                     
 caTools       1.17.1.1  2018-07-20 cran (@1.17.1.)                    
 clipr         0.4.1     2018-06-23 CRAN (R 3.5.0)                     
 compiler      3.5.0     2018-04-24 local                              
 curl          3.2       2018-03-28 CRAN (R 3.5.0)                     
 datasets    * 3.5.0     2018-04-24 local                              
 devtools      1.13.5    2018-02-18 CRAN (R 3.5.0)                     
 digest        0.6.15    2018-01-28 CRAN (R 3.5.0)                     
 graphics    * 3.5.0     2018-04-24 local                              
 grDevices   * 3.5.0     2018-04-24 local                              
 htmltools     0.3.6     2017-04-28 CRAN (R 3.5.0)                     
 htmlwidgets   1.2       2018-04-19 CRAN (R 3.5.0)                     
 httr          1.3.1     2017-08-20 CRAN (R 3.5.0)                     
 jsonlite      1.5       2017-06-01 CRAN (R 3.5.0)                     
 knitr         1.20      2018-02-20 CRAN (R 3.5.0)                     
 magick        1.9       2018-05-11 CRAN (R 3.5.0)                     
 magrittr      1.5       2014-11-22 CRAN (R 3.5.0)                     
 memoise       1.1.0     2017-04-21 CRAN (R 3.5.0)                     
 methods     * 3.5.0     2018-04-24 local                              
 openssl       1.0.1     2018-03-03 CRAN (R 3.5.0)                     
 R6            2.2.2     2017-06-17 CRAN (R 3.5.0)                     
 rappdirs      0.3.1     2016-03-28 cran (@0.3.1)                      
 Rcpp          0.12.18   2018-07-23 CRAN (R 3.5.0)                     
 RSelenium   * 1.7.3     2018-07-27 Github (ropensci/RSelenium@088db87)
 rsvg          1.3       2018-05-10 CRAN (R 3.5.0)                     
 semver        0.2.0     2017-01-06 cran (@0.2.0)                      
 slickR        0.3       2018-07-09 local                              
 stats       * 3.5.0     2018-04-24 local                              
 subprocess    0.8.2     2017-10-22 cran (@0.8.2)                      
 tools         3.5.0     2018-04-24 local                              
 utils       * 3.5.0     2018-04-24 local                              
 wdman       * 0.2.4     2018-07-21 cran (@0.2.4)                      
 withr         2.1.2     2018-03-15 CRAN (R 3.5.0)                     
 XML           3.98-1.12 2018-07-15 cran (@3.98-1.)                    
 xml2          1.2.0     2018-01-24 CRAN (R 3.5.0)                     
 yaml          2.2.0     2018-07-25 CRAN (R 3.5.0) 
```

</details>

### Please describe Expected behaviour

trying to download file via RSelenium using headless chrome

### Please describe Actual behaviour

no download is executed

### Steps to reproduce the behaviour

```r
eCaps <- list(
  chromeOptions = list(
    args = c('--headless','--disable-gpu', '--window-size=1280,800'),
    prefs = list(
      "profile.default_content_settings.popups" = 0L,
      "download.prompt_for_download" = FALSE,
      "download.default_directory" = getwd()
    )
  )
)  

cDrv <- wdman::chrome()

rD <- RSelenium::rsDriver(extraCapabilities = eCaps)

remDr <- rD$client

remDr$navigate('https://github.com/yonicd/covrpage/blob/master/R/sysdata.rda')

Sys.sleep(2)

webElem <- remDr$findElement(using = 'xpath',value = '//*[@id="raw-url"]')

webElem$clickElement()

list.files(getwd(),pattern = 'sysdata')

remDr$closeall()

cDrv$stop()
```

**Comment by juyeongkim** [comment]
@yonicd I finally got to try this out, and I found a solution!!!

Add this code after creating a remoteDrive object:

```R
remDr$queryRD(
  ipAddr = paste0(remDr$serverURL, "/session/", remDr$sessionInfo[["id"]], "/chromium/send_command"),
  method = "POST",
  qdata = list(
    cmd = "Page.setDownloadBehavior",
    params = list(
      behavior = "allow",
      downloadPath = getwd()
    )
  )
)
```

This sends a command to the headless chrome to allow downloading.

I follow [this python solution](https://stackoverflow.com/a/47366981).

**Comment by yonicd** [comment]
Wow. I would have never guessed that. Thank you!

**Comment by wjiarao** [comment]
A Bug when using head less Chrome, here was my code.

**> devtools::session_info()**
Session info ----------------------------------------------------------------------------------------------------
 setting  value                                              
 version  R version 3.4.1 (2017-06-30)                       
 system   x86_64, mingw32                                    
 ui       RStudio (1.1.383)                                  
 language (EN)                                               
 collate  Chinese (Simplified)_People's Republic of China.936
 tz       Asia/Taipei                                        
 date     2018-10-14                                         

Packages --------------------------------------------------------------------------------------------------------
 package     * version    date       source                               
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.3)                       
 base        * 3.4.1      2017-06-30 local                                
 binman      * 0.1.1      2018-07-18 CRAN (R 3.4.4)                       
 bitops        1.0-6      2013-08-17 CRAN (R 3.4.1)                       
 caTools       1.17.1.1   2018-07-20 CRAN (R 3.4.4)                       
 compiler      3.4.1      2017-06-30 local                                
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.3)                       
 curl          3.2        2018-03-28 CRAN (R 3.4.4)                       
 datasets    * 3.4.1      2017-06-30 local                                
 decapitated * 0.3.0      2018-10-10 Github (hrbrmstr/decapitated@842cc72)
 devtools      1.13.5     2018-02-18 CRAN (R 3.4.3)                       
 digest        0.6.17     2018-09-12 CRAN (R 3.4.4)                       
 graphics    * 3.4.1      2017-06-30 local                                
 grDevices   * 3.4.1      2017-06-30 local                                
 HARtools      0.0.5      2016-11-09 CRAN (R 3.4.4)                       
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.3)                       
 htmlwidgets   1.0        2018-01-20 CRAN (R 3.4.3)                       
 httr          1.3.1      2017-08-20 CRAN (R 3.4.3)                       
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.3)                       
 knitr         1.20       2018-02-20 CRAN (R 3.4.4)                       
 magick        1.9        2018-05-11 CRAN (R 3.4.4)                       
 magrittr      1.5        2014-11-22 CRAN (R 3.4.3)                       
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.4)                       
 methods     * 3.4.1      2017-06-30 local                                
 openssl       1.0.2      2018-07-30 CRAN (R 3.4.4)                       
 processx      3.2.0      2018-08-16 CRAN (R 3.4.4)                       
 ps            1.1.0      2018-08-10 CRAN (R 3.4.4)                       
 R6            2.2.2      2017-06-17 CRAN (R 3.4.3)                       
 rappdirs      0.3.1      2016-03-28 CRAN (R 3.4.3)                       
 Rcpp          0.12.16    2018-03-13 CRAN (R 3.4.4)                       
 RSelenium   * 1.7.4.9000 2018-10-12 Github (ropensci/RSelenium@7509b81)  
 rstudioapi    0.7        2017-09-07 CRAN (R 3.4.3)                       
 Rwordseg      0.2-1      2013-12-15 R-Forge (R 3.0.2)                    
 semver        0.2.0      2017-01-06 CRAN (R 3.4.3)                       
 stats       * 3.4.1      2017-06-30 local                                
 tools         3.4.1      2017-06-30 local                                
 utils       * 3.4.1      2017-06-30 local                                
 wdman       * 0.2.4      2018-07-21 CRAN (R 3.4.4)                       
 withr         2.1.1      2017-12-19 CRAN (R 3.4.3)                       
 XML           3.98-1.16  2018-08-19 CRAN (R 3.4.4)                       
 xml2          1.2.0      2018-01-24 CRAN (R 3.4.4)                       
 yaml          2.1.14     2016-11-12 url          

library(wdman)
library(binman)
library(RSelenium)

eCaps <- list(
  chromeOptions = list(
    args = c('--headless','--disable-gpu','--windows-size = 1280,800'),
    prefs = list(
      "profile.default_content_settings.popups" = 0L,
      "download.prompt_for_download" = FALSE,
      "download.default_directory" = getwd()
    )
    )
  )

cDrv <- wdman::chrome()

Error occur:
checking chromedriver versions:
BEGIN: PREDOWNLOAD
Error in open.connection(con, "rb") : 
  schannel: failed to receive handshake, SSL/TLS connection failed     

Headless Chrome can not be used, I find many way, but still not solved, version of chromedriver and selenium well, Some one can help me , thanks a lot.

**Comment by yonicd** [comment]
has this changed again? i cant seem to get the headless download to work again to a preset path. (without headless it works ok)

**Comment by QizhiSu** [comment]
@juyeongkim I did as you suggest, but I get an error: 

Selenium message:POST /session/2b7c93dec093bffbbc2e28e54bd5eaf8/chromium/send_command
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T21:30:10'
System info: host: 'SUKIS', ip: '192.168.174.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown

Error: 	 Summary: UnknownCommand
 	 Detail: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
	 Further Details: run errorDetails method

Any clue?
