### ISSUE TITLE
Starting with 0.27.0, the geckodriver binaries for Linux have .asc files, the presence of which breaks downloads

### ISSUE THREAD

**Issue by jspiewak** [ropensci/wdman#27]
Please fill the following template:

### Operating System
Any Linux

### Please describe Expected behaviour
geckodriver version 0.27.0 and newer can be downloaded.

### Please describe Actual behaviour
Downloading fails with the error

```
checking geckodriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
Creating directory: /mnt/home/jss/.local/share/binman_geckodriver/linux64/0.29.0
Downloading binary: https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz

Downloading binary: https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz.asc

Creating directory: /mnt/home/jss/.local/share/binman_geckodriver/linux64/0.28.0
Downloading binary: https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz

BEGIN: POSTDOWNLOAD
Error in (function (platform, file, processed, chmod)  : 
  /mnt/home/jss/.local/share/binman_geckodriver/linux64/0.29.0/geckodriver-v0.29.0-linux64.tar.gz.asc does not appear to be a zip or tar file.
```

### Steps to reproduce the behaviour

On a Linux machine (not macOS):

```
install.packages("RSelenium")
rD <- RSelenium::rsDriver(browser = "phantomjs")
```

**Comment by ravipatel4** [comment]
I encountered the same issue. Downgrading the version of RSelenium to 1.7.0 worked for me.

**Comment by juyeongkim** [comment]
Resolved with https://github.com/ropensci/wdman/commit/a01435f38a5c4198d1eade374aa82f51257bbaf8

**Comment by paul-rebman** [comment]
I'm also getting the same error running on linux through Github Actions. @jspiewak were you able to find a solution? Neither using RSelenium v. 1.7.0 or installing RSelenium straight from github worked for me.
